# Generated by Django 2.2.6 on 2019-10-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(verbose_name='Data da criação')),
                ('tipo_despesa', models.CharField(choices=[('remedio', 'remédio'), ('roupa', 'roupa'), ('alimentacao', 'alimentação'), ('educacao', 'educacao'), ('transporte', 'transporte'), ('outros', 'outros')], max_length=20, verbose_name='Tipo de despesa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('formaDePagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartaoCredito', 'Cartão de crédito'), ('cartaoDebito', 'Cartão de débito'), ('cartaoCrediario', 'Cartão crediário'), ('cheque', 'cheque')], max_length=20, verbose_name='Forma de pagamento')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('quitado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
            },
        ),
    ]
