# Generated by Django 2.2.6 on 2019-10-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='formaDePagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartaoCredito', 'Cartão de crédito'), ('cartaoDebito', 'Cartão de débito'), ('cartaoCrediario', 'Cartão crediário'), ('cheque', 'Cheque')], max_length=20, verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.CharField(choices=[('remedio', 'Remédio'), ('roupa', 'Roupa'), ('alimentacao', 'Alimentação'), ('educacao', 'Educacao'), ('transporte', 'Transporte'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de despesa'),
        ),
    ]
