# Generated by Django 2.2.6 on 2019-10-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0002_auto_20191023_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.CharField(choices=[('remedio', 'Remédio'), ('roupa', 'Roupa'), ('alimentacao', 'Alimentação'), ('educacao', 'Educação'), ('transporte', 'Transporte'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de despesa'),
        ),
    ]
